apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-liquidations-consumer-elastic
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-liquidations-consumer-elastic
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 75
